django_orm/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('university.urls', namespace='university')),
    path('', include('home.urls', namespace='home')),
]

home/urls.py
from django.urls import path
from .views import Home


app_name='home'
urlpatterns = [
    path('', Home.as_view(), name='home'),
]

university/urls.py
from django.urls import path
from . import views


app_name = "university"
urlpatterns = [
	path('values/', views.StudentList.as_view(), name='students'),
	path('q-function/', views.LessonList.as_view(), name='lessons'),
]

home/models.py
from django.db import models

# Create your models here.

university/models.py
from django.db import models


class Student(models.Model):
    name = models.CharField(max_length=100)
    age = models.CharField(max_length=2)
    about = models.TextField(default="This is a student")

    def __str__(self):
        return self.name


class Lesson(models.Model):
    name = models.CharField(max_length=100)
    students = models.ManyToManyField(Student)
    teacher = models.ForeignKey('Teacher', on_delete=models.CASCADE, related_name='lesson')
    description = models.TextField()

    def __str__(self):
        return self.name


class Teacher(models.Model):
    name = models.CharField(max_length=100)
    age = models.CharField(max_length=2)
    lessons = models.ManyToManyField(Lesson, related_name='teachers', blank=True)
    about = models.TextField(default="This is a teacher")

    def __str__(self):
        return self.name

home/views.py
from django.shortcuts import render
from django.views import View


class Home(View):
    def get(self, request):
        return render(request, 'home/index.html')

university/views.py
from django.shortcuts import render
from django.views import View
from django.db.models import Q
# Local apps
from .models import Student, Lesson, Teacher 


# values AND values_list
class StudentList(View):
	def get(self, request):
		students = Student.objects.all().values_list("name", "age")
		print(students)

		context = {'students': students}
		return render(request, 'university/values_valueslist.html', context)


# Q-functions
class LessonList(View):
	def get(self, request):
		lessons = Lesson.objects.filter(
			Q(teacher__name="Amir Amiri") &
			Q(students__name="Danial")
		)

		context = {'lessons': lessons}
		return render(request, 'university/q_function.html', context)

home/templates/home/index.html
{% extends 'base.html' %}


{% block content %}

    <ul style="font-size: 20px;">
        <div class="d-grid gap-2 col-6 mx-auto">
            <li class="btn btn-primary mb-3">
                <a href="{% url 'university:students' %}" style="text-decoration: none;" class="text text-white">
                    values & values_list</a>
            </li>
            <li class="btn btn-primary">
                <a href="{% url 'university:lessons' %}" style="text-decoration: none;" class="text text-white">
                    Q functions</a>
            </li>
        </div>
    </ul>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
	<title>Simple Boy / TipHub</title>
</head>
<body style="background-color: #c2c8ca;">

	<h2 class="text text-center mt-3">TipHub / Simple Boy</h2>
	<a href="{% url 'home:home' %}" class="btn btn-success" style="margin-left: 10px;">
		Home page</a>
	<hr><br>
	{% block content %}{% endblock %}

</body>
</html>

university/templates/university/index.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
	<title>Simple Boy / TipHub</title>
</head>
<body>

	<h2 class="text text-center mt-3">TipHub / values & values_list</h2>
	{% for student in students %}
		<p class="m-3">{{ student.0 }} : <span>{{ student.1 }}</span></p>
	{% endfor %}

</body>
</html>

university/templates/university/q_function.html
{% extends 'base.html' %}


{% block content %}

    {% for lesson in lessons %}
        <p class="m-3">{{ lesson }}</p>
    {% endfor %}

{% endblock %}

university/templates/university/values_valueslist.html
{% extends 'base.html' %}


{% block content %}

	{% for student in students %}
		<!-- values_list -->
		<p class="m-3">{{ student.0 }} : <span>{{ student.1 }}</span></p>
		<!-- values -->
		<!-- <p class="m-3">{{ student.name }} : <span>{{ student.age }}</span></p> -->
	{% endfor %}

{% endblock %}